trackersite/tracker/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.views.generic import DetailView, RedirectView

from tracker.models import Grant
from tracker import feeds

urlpatterns = patterns('',
    url(r'^tickets/(?:page/(?P<page>\d+)/)?$', 'tracker.views.ticket_list', name='ticket_list'),
    url(r'ticket/watch/(?P<pk>\d+)/?$', 'tracker.views.watch_ticket', name='watch_ticket'),
    url(r'^tickets/feed/$', feeds.LatestTicketsFeed(), name='ticket_list_feed'),
    url(r'^tickets/feed/submitted/$', feeds.SubmittedTicketsFeed(), name='ticket_submitted_feed'),
    url(r'^ticket/(?P<pk>\d+)/$', 'tracker.views.ticket_detail', name='ticket_detail'),
    url(r'^ticket/(?P<pk>\d+)/edit/$', 'tracker.views.edit_ticket', name='edit_ticket'),
    url(r'^ticket/(?P<pk>\d+)/edit/copypreexpeditures/$', 'tracker.views.copypreexpeditures', name='copypreexpeditures'),
    url(r'^ticket/(?P<pk>\d+)/edit/docs/$', 'tracker.views.edit_ticket_docs', name='edit_ticket_docs'),
    url(r'^ticket/(?P<pk>\d+)/edit/docs/new/$', 'tracker.views.upload_ticket_doc', name='upload_ticket_doc'),
    url(r'^ticket/(?P<pk>\d+)/edit/(?P<ack_type>[a-z_]+)/add/$', 'tracker.views.ticket_ack_add', name='ticket_ack_add'),
    url(r'^ticket/(?P<pk>\d+)/edit/acks/(?P<ack_id>\d+)/delete/$', 'tracker.views.ticket_ack_delete', name='ticket_ack_delete'),
    url(r'^ticket/(?P<ticket_id>\d+)/docs/(?P<filename>[-_\.A-Za-z0-9]+\.[A-Za-z0-9]+)$', 'tracker.views.download_document', name='download_document'),
    url(r'^ticket/new/$', 'tracker.views.create_ticket', name='create_ticket'),
    url(r'^topics/$', 'tracker.views.topic_list', name='topic_list'),
    url(r'^topics/finance/$', 'tracker.views.topic_finance', name='topic_finance'),
    url(r'^topics/acks/$', 'tracker.views.topic_content_acks_per_user', name='topic_content_acks_per_user'),
    url(r'^topics/acks/acks\.csv$', 'tracker.views.topic_content_acks_per_user_csv', name='topic_content_acks_per_user_csv'),
    url(r'^topic/(?P<pk>\d+)/$', 'tracker.views.topic_detail', name='topic_detail'),
    url(r'^subtopic/(?P<pk>\d+)/$', 'tracker.views.subtopic_detail', name='subtopic_detail'),
    url(r'^topic/watch/(?P<pk>\d+)/$', 'tracker.views.watch_topic', name='watch_topic'),
    url(r'^topic/(?P<pk>\d+)/feed/$', feeds.TopicTicketsFeed(), name='topic_ticket_feed'),
    url(r'^topic/(?P<pk>\d+)/feed/submitted/$', feeds.TopicSubmittedTicketsFeed(), name='topic_submitted_ticket_feed'),
    url(r'^grant/(?P<slug>[-\w]+)/$', DetailView.as_view(model=Grant), name='grant_detail'),
    url(r'^users/$', 'tracker.views.user_list', name='user_list'),
    url(r'^users/(?P<username>[^/]+)/$', 'tracker.views.user_detail', name='user_detail'),
    url(r'^my/details/$', 'tracker.views.user_details_change', name='user_details_change'),
    url(r'^my/mutenotifications/$', 'tracker.views.mute_notifications', name='mute_notifications'),
    url(r'^transactions/$', 'tracker.views.transaction_list', name='transaction_list'),
    url(r'^transactions/feed/$', feeds.TransactionsFeed(), name='transactions_feed'),
    url(r'^transactions/transactions\.csv$', 'tracker.views.transactions_csv', name='transactions_csv'),
    url(r'^cluster/(?P<pk>\d+)/$', 'tracker.views.cluster_detail', name='cluster_detail'),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^old/(?P<url>(?:tickets?/|topics?/|)(?:\d+/|new/)?)$', RedirectView.as_view(url='/%(url)s', permanent=True)),
    url(r'^js/topics\.js$', 'tracker.views.topics_js', name='topics_js'),
    url(r'^admin/users/$', 'tracker.views.admin_user_list', name='admin_user_list'),
    url(r'^export/$', 'tracker.views.export', name='export'),
    url(r'^import/$', 'tracker.views.importcsv', name='importcsv'),
    url(r'tickets/json/(?P<lang>.+).json$', 'tracker.views.tickets', name='tickets'),
)

trackersite/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.http import HttpResponse
from django.views.generic import RedirectView, TemplateView
from django.contrib import admin
from django.contrib.auth import views as auth

import tracker.urls
import users.urls

admin.autodiscover()

js_info_dict = {
    'packages': ('django.contrib.admin'),
    # local site stuff should be covered by LOCALE_PATHS common setting
}

urlpatterns = patterns('',
    url(r'^$', RedirectView.as_view(url='tickets/', permanent=False), name='index'),
    url(r'', include(tracker.urls)), # tracker urls are included directly in web root
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/', include(users.urls)),
    url(r'^lang/$', TemplateView.as_view(template_name='choose_language.html'), name='choose_language'),
    url(r'^lang/set/$', 'django.views.i18n.set_language', name='set_language'),
    url(r'^js/i18n\.js$', 'django.views.i18n.javascript_catalog', js_info_dict),
    url(r'^robots\.txt$', lambda x: HttpResponse("User-agent: *\nDisallow: /\n", content_type="text/plain")),
)

trackersite/tracker/models.py
# -*- coding: utf-8 -*-
import datetime
import decimal

from django_comments.signals import comment_was_posted
from django.db.models.signals import pre_save, post_save, post_delete
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db import models
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _, string_concat
from django.utils.html import escape
from django.utils.safestring import mark_safe
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.core.validators import RegexValidator
from django.core.urlresolvers import NoReverseMatch
from django.core.cache import cache
from django import template
from django.template.loader import get_template
import re
import json

from users.models import UserWrapper

PAYMENT_STATUS_CHOICES = (
    ('n_a', _('n/a')),
    ('unpaid', _('unpaid')),
    ('partially_paid', _('partially paid')),
    ('paid', _('paid')),
    ('overpaid', _('overpaid')),
)

ACK_TYPES = (
    ('user_precontent', _('presubmitted')),
    ('precontent', _('preaccepted')),
    ('user_content', _('submitted')),
    ('content', _('accepted')),
    ('user_docs', _('expense documents submitted')),
    ('docs', _('expense documents filed')),
    ('archive', _('archived')),
    ('close', _('closed')),
)

NOTIFICATION_TYPES = [
    ('comment', _('Comment added')),
    ('supervisor_notes', _('Supervisor notes changed')),
    ('ticket_new', _('New ticket was created')),
    ('ack_add', _('Ack added')),
    ('ack_remove', _('Ack removed')),
    ('ticket_change', _('Ticket changed')),
    ('ticket_change_all', _('Ticket changed [for requestor]')),
    ('preexpeditures_change', _('Preexpeditures changed')),
    ('expeditures_change', _('Expeditures changed')),
    ('media_change', _('Media changed')),
]

USER_EDITABLE_ACK_TYPES = ('user_precontent', 'user_content', 'user_docs')

def uber_ack(ack_type):
    """ Return 'super-ack' for given user-editable ack. """
    return {
        'user_precontent': 'precontent',
        'user_content': 'content',
        'user_docs':'docs',
    }[ack_type]

class PercentageField(models.SmallIntegerField):
    """ Field that holds a percentage. """
    def formfield(self, **kwargs):
        defaults = {'min_value': 0, 'max_value':100}
        defaults.update(kwargs)
        return super(PercentageField, self).formfield(**defaults)

class CachedModel(models.Model):
    """ Model which has some values cached """

    def _get_item_key(self, name):
        return u'm:%s:%s:%s' % (self.__class__.__name__, self.id, name)

    def _get_version_key(self):
        return u'm:%s:%s:_version' % (self.__class__.__name__, self.id)

    def _cache_version(self):
        return cache.get(self._get_version_key()) or 1

    def flush_cache(self):
        cache.set(self._get_version_key(), self._cache_version() + 1)
    flush_cache.alters_data = True

    @staticmethod
    def cached_getter(raw_method):
        def wrapped(self):
            key = self._get_item_key(raw_method.__name__)
            version = self._cache_version()
            cached = cache.get(key, version=version)
            if cached is not None:
                return cached
            else:
                value = raw_method(self)
                cache.set(key, value, version=version)
                return value

        return wrapped

    class Meta:
        abstract = True
cached_getter = CachedModel.cached_getter

class DecimalRangeField(models.DecimalField):
    def __init__(self, verbose_name=None, name=None, min_value=None, max_value=None, **kwargs):
        self.min_value, self.max_value = min_value, max_value
        models.DecimalField.__init__(self, verbose_name, name, **kwargs)
    def formfield(self, **kwargs):
        defaults = {'min_value': self.min_value, 'max_value': self.max_value }
        defaults.update(kwargs)
        return super(DecimalRangeField, self).formfield(**defaults)

class Ticket(CachedModel):
    """ One unit of tracked / paid stuff. """
    created = models.DateTimeField(_('created'), auto_now_add=True)
    updated = models.DateTimeField(_('updated'))
    event_date = models.DateField(_('event date'), blank=True, null=True, help_text=_('Date of the event this ticket is about'))
    requested_user = models.ForeignKey('auth.User', verbose_name=_('requested by'), blank=True, null=True, help_text=_('User who created/requested for this ticket'))
    requested_text = models.CharField(verbose_name=_('requested by (text)'), blank=True, max_length=30, help_text=_('Text description of who requested for this ticket, in case user is not filled in'))
    summary = models.CharField(_('summary'), max_length=100, help_text=_('Headline summary for the ticket'))
    topic = models.ForeignKey('tracker.Topic', verbose_name=_('topic'), help_text=_('Project topic this ticket belongs to'))
    subtopic = models.ForeignKey('tracker.Subtopic', blank=True, null=True, verbose_name=_('subtopic'), help_text=_('Subtopic this ticket belongs to (if you don\'t know, leave this empty)'))
    rating_percentage = PercentageField(_('rating percentage'), blank=True, null=True, help_text=_('Rating percentage set by topic administrator'), default=100)
    mandatory_report = models.BooleanField(_('report mandatory'), default=False, help_text=_('Is report mandatory?'))
    report_url = models.CharField(_('report url'), blank=True, max_length=255, default='', help_text=_('URL to your report, if you want to report something (or if your report is mandatory per topic administrator).'))
    event_url = models.URLField(_('event url'), blank=True, help_text=_('Link to a public page describing the event, if it exist'))
    description = models.TextField(_('description'), blank=True, help_text=_("Space for further notes. If you're entering a trip tell us where did you go and what you did there."))
    supervisor_notes = models.TextField(_('supervisor notes'), blank=True, help_text=_("This space is for notes of project supervisors and accounting staff."))
    deposit = DecimalRangeField(_('deposit'), default=0, min_value=0,
                                decimal_places=2, max_digits=8,
                                help_text=_("If you are requesting a financial deposit, please fill here its amount. Maximum amount is sum of preexpeditures. If you aren't requesting a deposit, fill here 0."))
    cluster = models.ForeignKey('Cluster', blank=True, null=True, on_delete=models.SET_NULL)
    payment_status = models.CharField(_('payment status'), max_length=20, default='n/a', choices=PAYMENT_STATUS_CHOICES)
    imported = models.BooleanField(_('imported'), default=False, help_text=_('Was this ticket imported from older Tracker version?'))

    @staticmethod
    def currency():
        return settings.TRACKER_CURRENCY

    def update_payment_status(self, save_afterwards=True):
        paid_len = len(self.expediture_set.filter(paid=True))
        all_len = len(self.expediture_set.all())

        if all_len == 0:
            self.payment_status = 'n/a'
        elif paid_len == 0 and all_len > 0:
            self.payment_status = 'unpaid'
        elif paid_len < all_len:
            self.payment_status = 'partially_paid'
        elif paid_len == all_len:
            self.payment_status = 'paid'

        if save_afterwards:
            self.save(just_payment_status=True)
    update_payment_status.alters_data = True

    def save(self, *args, **kwargs):
        just_payment_status = kwargs.pop('just_payment_status', False)
        if not just_payment_status:
            self.updated = datetime.datetime.now()

        if self.event_date == None:
            self.event_date = datetime.date.today()

        if not just_payment_status:
            self.update_payment_status(save_afterwards=False)

        super(Ticket, self).save(*args, **kwargs)

        self.flush_cache()

    def _note_comment(self, **kwargs):
        self.save()

    @staticmethod
    def get_tickets_with_state(state):
        tickets = Ticket.objects.all()
        result = []
        for ticket in tickets:
            if ticket.state_str() == state:
                result.append(ticket)
        return result

    def admin_topic(self):
        return '%s (%s)' % (self.topic, self.topic.grant)

    def is_concept(self):
        return len(self.ack_set()) == 0

    def state_str(self):
        if self.imported:
            return _('historical')

        acks = self.ack_set()
        if 'close' in acks:
            return _('closed')
        elif 'archive' in acks:
            return _('archived')
        elif 'content' in acks:
            if not self.rating_percentage:
                return _('waiting for content rating')

            if 'docs' in acks:
                return _('complete')
            elif 'user_docs' in acks:
                return _('waiting for filing of documents')
            else:
                return _('waiting for document submission')
        elif 'precontent' in acks:
            if 'user_content' in acks:
                return _('waiting for approval')
            else:
                return _('waiting for submitting')
        else:
            if 'user_precontent' in acks:
                return _('waiting for preapproval')
            elif 'user_content' in acks:
                return _('waiting for approval')
            else:
                return _('draft')
    state_str.admin_order_field = 'state'
    state_str.short_description = _('state')

    def __unicode__(self):
        return '%s: %s' % (self.id , self.summary)

    @cached_getter
    def requested_by(self):
        if self.requested_user != None:
            return self.requested_user.username
        else:
            return self.requested_text
    requested_by.short_description = _('requested by')

    def requested_by_html(self):
        if self.requested_user != None:
            return UserWrapper(self.requested_user).get_html_link()

trackersite/tracker/templates/tracker/admin_index_override.html
{% extends "admin/index.html" %}
{% load i18n %}

{% block content %}
<div id="content-main">

{% if app_list %}
    {% for app in app_list %}
        <div class="module">
        <table summary="{% blocktrans with app.name as name %}Models available in the {{ name }} application.{% endblocktrans %}">
        <caption><a href="{{ app.app_url }}" class="section">{% blocktrans with app.name as name %}{{ name }}{% endblocktrans %}</a></caption>
        {% for model in app.models %}
            <tr>
            {% if model.perms.change %}
                <th scope="row"><a href="{{ model.admin_url }}">{{ model.name }}</a></th>
            {% else %}
                <th scope="row">{{ model.name }}</th>
            {% endif %}

            {% if model.perms.add %}
                <td><a href="{{ model.admin_url }}add/" class="addlink">{% trans 'Add' %}</a></td>
            {% else %}
                <td>&nbsp;</td>
            {% endif %}

            {% if model.perms.change %}
                <td><a href="{{ model.admin_url }}" class="changelink">{% trans 'Change' %}</a></td>
            {% else %}
                <td>&nbsp;</td>
            {% endif %}
            </tr>
        {% endfor %}
        </table>
        </div>
    {% endfor %}    
    
    <div class="module">
        <table>
            <caption>{% trans "User list" %}</caption>
            <tr><th scope="row"><a href="{% url "admin_user_list" %}">{% trans "Tracker users" %}</a></th><td>&nbsp;</td><td>&nbsp;</td></tr>
        </table>
    </div>
    
{% else %}
    <p>{% trans "You don't have permission to edit anything." %}</p>
{% endif %}
</div>
{% endblock %}

trackersite/tracker/templates/tracker/cluster_detail.html
{% extends "base.html" %}
{% load i18n trackertags %}

{% block title %}{% blocktrans with cid=cluster.id %}Cluster {{cid}}{% endblocktrans %}{% endblock %}

{% block content %}
<p class="nav"><a href="{% url "ticket_list" %}">{% trans "index" %}</a> &gt; <a href="{% url "transaction_list" %}">{% trans "transactions" %}</a> &gt;</p>
<h1>{% blocktrans with cid=cluster.id %}Cluster {{cid}}{% endblocktrans %}</h1>

<p>{% trans "Payment status" %}: {% trans cluster.ticket_set.all.0.get_payment_status_display %}</p>

<h2>{% trans "Tickets" %}</h2>
{% with ticket_list=cluster.ticket_set.all %}
{% include "tracker/ticket_table.html" with show_expenses="True" show_topics="True" show_requester="True" summary_item=ticket_summary total_desc=_("Total tickets") total_colspan=5 %}
{% endwith %}

{% if cluster.transaction_set.all.count > 0 %}
<h2>{% trans "Transactions" %}</h2>
<table class="table table-striped table-hover"><tr><th>{% trans "Date" %}</th><th>{% trans "User" %}</th><th>{% trans "Amount" %}</th><th>{% trans "Description" %}</th><th>{% trans "Tickets" %}</th><th>{% trans "Accounting info" %}</th></tr>
{% for t in cluster.transaction_set.all %}
<tr><td>{{t.date}}</td><td>{{t.other_party_html}}</td><td class="money">{{t.amount|money}}</td><td>{{t.description}}</td>
<td>{% for ticket in t.tickets_by_id %}<a href="{{ticket.get_absolute_url}}" title="{{ticket.summary}} ({{ticket.sort_date}})">{{ticket.id}}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</td>
<td>{{t.accounting_info}}</td></tr>
{% endfor %}
<tr class="total first_total">
<td colspan="2">{% trans "Total transactions" %}</td>
<td class="money">{{cluster.total_transactions|money}}</td>
<td colspan="3"></td>
</tr>
</table>
{% endif %}

{% endblock content %}

trackersite/tracker/templates/tracker/create_ticket.html
{% extends "tracker/generic/create_ticket.html" %}
{% block head %}
{{block.super}}
<script type="text/javascript">
	$( document ).ready(function () {
		$('#copytopreexpeditures').hide();
	});
</script>
{% endblock %}

trackersite/tracker/templates/tracker/edit_ticket.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Edit" %}: {{ticket.summary}}{% endblock %}

{% block content %}
<p class="nav"><a href="{% url "ticket_list" %}" class="btn btn-primary">{% trans "index" %}</a> &gt; <a href="{% url "ticket_detail" ticket.id %}">{{ticket.summary}}</a> &gt;</p>
<h1>{% trans "Edit" %}: {{ticket.summary}}</h1>

<p>{% if user_can_edit_documents %}<a href="{% url "edit_ticket_docs" ticket.id %}">{% trans "edit ticket documents" %}</a>{% endif %} {% if user_can_copy_preexpeditures %}<a href="{% url "copypreexpeditures" ticket.id %}">{% trans "copy preexpeditures to expeditures" %}</a>{% endif %}</p>

{% block above_form %}{% endblock %}
{% url "edit_ticket" ticket.id as action %}
{% include "tracker/ticket_form.html" with submit=_("save") %}
{% block below_form %}{% endblock %}
{% endblock content %}

trackersite/tracker/templates/tracker/grant_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{{grant.full_name}}{% endblock %}

{^

{% block content %}
<p class="nav"><a href="{% url "ticket_list" %}">{% trans "index" %}</a> &gt; <a href="{% url "topic_list" %}">{% trans "topics" %}</a> &gt;</p>
<h1>{{grant.full_name}}</h1>
{% if grant.description %}<div>{{ grant.description|safe|linebreaks }}</div>{% endif %}

{% include "tracker/topic_table.html" with topic_list=grant.topic_set.all grant=grant %}

{% endblock content %}

trackersite/tracker/templates/tracker/subtopic_detail.html
{% extends "base.html" %}
{% load i18n comments recaptcha2 %}

{% block title %}{{ subtopic.name }}{% endblock %}

{% block content %}
<p class="nav"><a href="{% url "ticket_list" %}">{% trans "index" %}</a> &gt; <a href="{% url "topic_list" %}">{% trans "topics" %}</a> &gt; <a href="{{subtopic.topic.grant.get_absolute_url}}">{{subtopic.topic.grant.short_name}}</a> &gt; <a href="">{{ subtopic.topic }}</a> &gt;</p>
<h1>{{ subtopic.name }}</h1>

{% if subtopic.description %}<div>{{ subtopic.description|safe|linebreaks }}</div>{% endif %}

{% if subtopic.ticket_set.all|length > 0 %}
<h2>{% trans "Tickets" %}</h2>
{% include "tracker/ticket_table.html" with ticket_list=subtopic.ticket_set.all show_media=subtopic.topic.ticket_media show_expenses=subtopic.topic.ticket_expenses summary_item=subtopic show_requester="True" total_desc=_("Total for this subtopic") total_colspan=4 %}
{% endif %}
{% endblock %}

trackersite/tracker/templates/tracker/topic_list.html
{% extends "tracker/generic/topic_list.html" %}

trackersite/tracker/templates/tracker/topic_table.html
{% load i18n %}
{% if topic_list %}
<table id="topic_table" class="table table-striped table-hover"><thead><tr>
<th rowspan="2">{% trans "Topic" %}</th>
{% if show_grants %}<th rowspan="2"><abbr title="{% trans "Grant" %}">{% filter slice:":2" %}{% trans "Grant" %}{% endfilter %}<abbr></th>{% endif %}
<th rowspan="2">{% trans "Tickets" %}</th>
<th rowspan="2">{% trans "Paid wages" %}</th>
<th rowspan="2">{% trans "Paid together" %}</th>
<th colspan="5" class="smaller">{% trans "Tickets per payment status" %}</th>
<th rowspan="2">{% trans "Administrators" %}</th>
</tr>
<th><abbr title="{% trans "no payment required" %}">{% trans "n/a" %}</abbr></th>
<th><abbr title="{% trans "unpaid" %}">0</abbr></th>
<th><abbr title="{% trans "partially paid" %}">&lt;</abbr></th>
<th><abbr title="{% trans "paid" %}">=</abbr></th>
<th><abbr title="{% trans "overpaid" %}">&gt;</abbr></th>
</tr></thead>
<tbody>
{% for topic in topic_list %}{% with tpps=topic.tickets_per_payment_status %}
<tr>
<td><a href="{% url "topic_detail" topic.id %}">{{topic.name}}</a></td>
{% if show_grants %}<td><a href="{{topic.grant.get_absolute_url}}" title="{{topic.grant.full_name}}">{{topic.grant.short_name}}</a></td>{% endif %}
<td>{{topic.ticket_set.count}}</td>
<td>{{topic.paid_wages}} {% trans "CZK" %}</td>
<td>{{topic.paid_together}} {% trans "CZK" %}</td>
<td{% if tpps.n_a %} class="payment_cell n_a" {% endif %}>{{tpps.n_a}}</td>
<td{% if tpps.unpaid %} class="payment_cell unpaid"{% endif %}>{{tpps.unpaid}}</td>
<td{% if tpps.partially_paid %} class="payment_cell partially_paid"{% endif %}>{{tpps.partially_paid}}</td>
<td{% if tpps.paid %} class="payment_cell paid"{% endif %}>{{tpps.paid}}</td>
<td{% if tpps.overpaid %} class="payment_cell overpaid"{% endif %}>{{tpps.overpaid}}</td>
<td>{% for admin in topic.admin.all %}{{ admin.username }}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
</tr>
{% endwith %}{% endfor %}
</tbody>
{% if grant %}
<tr>
<td>{% trans "Total" %}</td>
<td>{{grant.total_tickets}}</td>
<td>{{grant.total_paid_wages}} {% trans "CZK" %}</td>
<td>{{grant.total_paid_together}} {% trans "CZK" %}</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
{% endif %}
</table>

{% else %}
<p>{% trans "No topics available." %}</p>
{% endif %}

trackersite/tracker/templates/tracker/user_list.html
{% extends "base.html" %}
{% load i18n trackertags %}

{% block title %}{% trans "User list" %}{% endblock %}

{% block content %}
<p class="nav"><a href="{% url "ticket_list" %}">{% trans "index" %}</a> &gt;</p>
<h1>{% trans "User list" %}</h1>

<span class="hidden" id="custom-ordering-datatables">[[0, "desc"]]</span>
<table class="table table-striped table-hover">
    <thead>
            <tr><th rowspan="2">{% trans "User" %}</th><th rowspan="2">{% trans "Tickets" %}<th colspan="2">{% trans "Media" %}</th><th rowspan="2">{% trans "Accepted expeditures" %}</th><th rowspan="2">{% trans "Transactions total" %}</th></tr>
            <tr><th><abbr title="{% trans "Item count" %}">{% trans "Itm." %}</abbr></th><th><abbr title="{% trans "File count" %}">{% trans "Fil." %}</abbr></th></tr>
    </thead>

    <tbody>
            {% for u in user_list %}{% with tu=u.trackerprofile %}
            <tr><td><a href="{{tu.get_absolute_url}}">{{u}}</a></td><td>{{u.ticket_set.count|default:""}}</td><td>{{tu.media_count.objects|default:""}}</td><td>{{tu.media_count.media|default:""}}</td><td class="money">{% if tu.accepted_expeditures %}{{tu.accepted_expeditures|money}}{% endif %}</td><td class="money">{% if tu.paid_expeditures %}{{tu.paid_expeditures|money}}{% endif %}</td></tr>
            {% endwith %}{% endfor %}
            
            {% if unassigned %}{% with u=unassigned %}
            <tr><td><abbr title="{% trans "Tickets not assigned to any tracker user" %}">{% trans "unassigned" %}</abbr></td><td>{{u.ticket_count}}</td><td>{{u.media.objects|default:""}}</td><td>{{u.media.media|default:""}}</td><td class="money">{% if u.accepted_expeditures %}{{u.accepted_expeditures|money}}{% endif %}</td><td></td></tr>
            {% endwith %}{% endif %}
    </tbody>

    <tfoot>
            <tr class="total first_total"><td>{% trans "Total" %}</td><td>{{totals.ticket_count}}</td><td>{{totals.media.objects}}</td><td>{{totals.media.media}}</td><td class="money">{{totals.accepted_expeditures|default:0|money}}</td><td class="money">{{totals.transactions|default:0|money}}</td></tr>
    </tfoot>

</table>
{% endblock content %}